In [73]:
import pandas as pd

In [74]:
data=pd.read_csv(r'C:\Users\ASUS\Downloads\DataCoSupplyChainDataset.csv')

In [75]:
data

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [76]:
data1=pd.DataFrame(data)

In [77]:
data1.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [6]:
#display all the columns name
data1.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [7]:
#datatype of all the columns
data1.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [8]:
#display no of rows given in data
data.count()

Type                             180519
Days for shipping (real)         180519
Days for shipment (scheduled)    180519
Benefit per order                180519
Sales per customer               180519
Delivery Status                  180519
Late_delivery_risk               180519
Category Id                      180519
Category Name                    180519
Customer City                    180519
Customer Country                 180519
Customer Email                   180519
Customer Fname                   180519
Customer Id                      180519
Customer Lname                   180511
Customer Password                180519
Customer Segment                 180519
Customer State                   180519
Customer Street                  180519
Customer Zipcode                 180516
Department Id                    180519
Department Name                  180519
Latitude                         180519
Longitude                        180519
Market                           180519
Order City                       180519
Order Country                    180519
Order Customer Id                180519
order date (DateOrders)          180519
Order Id                         180519
Order Item Cardprod Id           180519
Order Item Discount              180519
Order Item Discount Rate         180519
Order Item Id                    180519
Order Item Product Price         180519
Order Item Profit Ratio          180519
Order Item Quantity              180519
Sales                            180519
Order Item Total                 180519
Order Profit Per Order           180519
Order Region                     180519
Order State                      180519
Order Status                     180519
Order Zipcode                     24840
Product Card Id                  180519
Product Category Id              180519
Product Description                   0
Product Image                    180519
Product Name                     180519
Product Price                    180519
Product Status                   180519
shipping date (DateOrders)       180519
Shipping Mode                    180519
dtype: int64

In [9]:
data1.shape[1]

53

In [10]:
#find empty values of all coloumns
null_data=data.isnull()

In [11]:
null_data.head(5)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False

In [81]:
#adding two customer name
cust_fullname=data1['Customer Fname']+' '+data1['Customer Lname']

In [82]:
cust_fullname.head(10)

0       Cally Holloway
1           Irene Luna
2    Gillian Maldonado
3            Tana Tate
4       Orli Hendricks
5     Kimberly Flowers
6    Constance Terrell
7        Erica Stevens
8        Nichole Olsen
9       Oprah Delacruz
dtype: object

In [83]:
data1['Customer name']=cust_fullname

In [84]:
data1.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode',
       'Customer name'],
      dtype='object')

In [85]:
data1

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,Customer name
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class,Cally Holloway
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class,Irene Luna
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class,Gillian Maldonado
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class,Tana Tate
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class,Orli Hendricks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class,Maria Peterson
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class,Ronald Clark
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class,John Smith
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class,Mary Smith
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class,Andrea Ortega

In [136]:
data.drop(columns =["Customer Fname"], inplace = True)#dropping the columns as new column 'Customer name ' added

In [137]:
data.drop(columns =["Customer Lname"], inplace = True)

In [138]:
data.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Id',
       'Customer Password', 'Customer Segment', 'Customer State',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'order date (DateOrders)', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id',
       'Product Category Id', 'Product Description', 'Product Image',
       'Product Name', 'Product Price', 'Product Status',
       'shipping date (DateOrders)', 'Shipping Mode', 'Customer name',
       'Customer Street Code', 'Customer Street Name'],
      dtype='object')

In [151]:
#6.split the column customer street and get customer street code and customer street name
n = data1["Customer Street"].str.split(" ", n = 1, expand = True)

In [152]:
n

           0                      1
0       5365    Noble Nectar Island
1       2679            Rustic Loop
2       8510        Round Bear Gate
3       3200             Amber Bend
4       8671    Iron Anchor Corners
...      ...                    ...
180514  1322            Broad Glade
180515  7330       Broad Apple Moor
180516    97        Burning Landing
180517  2585  Silent Autumn Landing
180518   697          Little Meadow

[180519 rows x 2 columns]

In [88]:
data["Customer Street Code"]= n[0]#new column addition

In [89]:
data["Customer Street Name"]= n[1]

In [90]:
data.drop(columns =["Customer Street"], inplace = True)

In [91]:
data.head(5)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,Customer name,Customer Street Code,Customer Street Name
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class,Cally Holloway,5365,Noble Nectar Island
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class,Irene Luna,2679,Rustic Loop
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class,Gillian Maldonado,8510,Round Bear Gate
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class,Tana Tate,3200,Amber Bend
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class,Orli Hendricks,8671,Iron Anchor Corners

In [100]:
#7.Which is shipping prefferd most in each country
Shipping_details=data1.groupby(['Order Country','Shipping Mode'])

In [135]:
Shipping_details.size().nlargest(50)

Order Country         Shipping Mode
Estados Unidos        Standard Class    14676
M�xico                Standard Class     7835
Francia               Standard Class     7684
Alemania              Standard Class     5691
Australia             Standard Class     5085
Estados Unidos        Second Class       4939
Brasil                Standard Class     4877
Reino Unido           Standard Class     4391
Estados Unidos        First Class        3824
China                 Standard Class     3501
Italia                Standard Class     3081
India                 Standard Class     2764
Francia               Second Class       2714
M�xico                Second Class       2705
Indonesia             Standard Class     2445
Honduras              Standard Class     2336
Espa�a                Standard Class     2267
El Salvador           Standard Class     2258
Rep�blica Dominicana  Standard Class     2169
Cuba                  Standard Class     2164
Francia               First Class        2043
M�xico                First Class        2017
Turqu�a               Standard Class     2003
Alemania              Second Class       1820
Australia             Second Class       1699
Guatemala             Standard Class     1676
Nicaragua             Standard Class     1669
Alemania              First Class        1580
Brasil                Second Class       1499
Reino Unido           Second Class       1461
Nigeria               Standard Class     1402
Estados Unidos        Same Day           1401
Filipinas             Standard Class     1286
Panam�                Standard Class     1258
Brasil                First Class        1242
Argentina             Standard Class     1199
Australia             First Class        1137
Pa�ses Bajos          Standard Class     1107
China                 Second Class       1102
Colombia              Standard Class     1085
Reino Unido           First Class        1061
India                 Second Class       1038
Nueva Zelanda         Standard Class      975
Ir�n                  Standard Class      934
Italia                Second Class        881
Indonesia             Second Class        846
China                 First Class         821
Austria               Standard Class      817
Francia               Same Day            781
India                 First Class         753
dtype: int64

In [114]:
#8.which product having highest benefit order
data.groupby('Category Name').agg({'Benefit per order':'max'})['Benefit per order'].nlargest(1)

Category Name
Strength Training    911.799988
Name: Benefit per order, dtype: float64

In [166]:
data.groupby('Category Name').agg({'Benefit per order':'min'}).sort_values(by='Benefit per order',ascending=False).iloc[0:5]

               Benefit per order
Category Name
CDs                   -23.610001
Toys                  -25.969999
Books                 -76.150002
Video Games          -104.110001
Baby                 -138.779999

In [144]:
#9.Which city has highest customer
Customer_details=data1.groupby(['Customer City'])

In [145]:
for name,Group in Customer_details :
    print('\nGroup')
    print(name)

Group
Aguadilla

Group
Alameda

Group
Albany

Group
Albuquerque

Group
Algonquin

Group
Alhambra

Group
Allentown

Group
Alpharetta

Group
Amarillo

Group
Anaheim

Group
Ann Arbor

Group
Annandale

Group
Annapolis

Group
Antioch

Group
Apex

Group
Apopka

Group
Arecibo

Group
Arlington

Group
Arlington Heights

Group
Asheboro

Group
Astoria

Group
Atlanta

Group
Augusta

Group
Aurora

Group
Austin

Group
Azusa

Group
Bakersfield

Group
Baldwin Park

Group
Ballwin

Group
Baltimore

Group
Bartlett

Group
Bay Shore

Group
Bayamon

Group
Bayonne

Group
Baytown

Group
Beaverton

Group
Bell Gardens

Group
Bellflower

Group
Bellingham

Group
Beloit

Group
Bend

Group
Bensalem

Group
Berwyn

Group
Billings

Group
Birmingham

Group
Bismarck

Group
Blacksburg

Group
Bloomfield

Group
Bolingbrook

Group
Bountiful

Group
Bowling Green

Group
Brandon

Group
Brentwood

Group
Bridgeton

Group
Brighton

Group
Bristol

Group
Brockton

Group
Broken Arrow

Group
Bronx

Group
Brooklyn

Group
Broomfield

Group
Brownsville

Group
Buena Park

Group
Buffalo

Group
Burnsville

Group
CA

Group
Caguas

Group
Campbell

Group
Canoga Park

Group
Canovanas

Group
Canton

Group
Canyon Country

Group
Carlisle

Group
Carlsbad

Group
Carmichael

Group
Carol Stream

Group
Carolina

Group
Carrollton

Group
Carson

Group
Cary

Group
Catonsville

Group
Cayey

Group
Cerritos

Group
Chambersburg

Group
Chandler

Group
Chapel Hill

Group
Charlotte

Group
Chesapeake

Group
Chicago

Group
Chicago Heights

Group
Chillicothe

Group
Chino

Group
Chino Hills

Group
Chula Vista

Group
Cicero

Group
Cincinnati

Group
Citrus Heights

Group
Clarksville

Group
Clearfield

Group
Clementon

Group
Cleveland

Group
Clovis

Group
College Station

Group
Colorado Springs

Group
Colton

Group
Columbia

Group
Columbus

Group
Compton

Group
Conway

Group
Cordova

Group
Corona

Group
Costa Mesa

Group
Crown Point

Group
Crystal Lake

Group
Cumberland

Group
Cupertino

Group
Cypress

Group
Dallas

Group
Daly City

Group
Danbury

Group
Davis

Group
Dayton

Group
Dearborn

Group
Decatur

Group
Del Rio

Group
Denton

Group
Denver

Group
Des Plaines

Group
Detroit

Group
Diamond Bar

Group
Dorchester Center

Group
Douglasville

Group
Doylestown

Group
Dubuque

Group
Duluth

Group
Dundalk

Group
Eagle Pass

Group
East Brunswick

Group
East Lansing

Group
Edinburg

Group
Edison

Group
El Cajon

Group
El Centro

Group
El Monte

Group
El Paso

Group
Elgin

Group
Elk Grove

Group
Elmhurst

Group
Elyria

Group
Encinitas

Group
Endicott

Group
Enfield

Group
Englewood

Group
Escondido

Group
Eugene

Group
Everett

Group
Ewa Beach

Group
Fairfield

Group
Far Rockaway

Group
Fargo

Group
Fayetteville

Group
Federal Way

Group
Findlay

Group
Florissant

Group
Flushing

Group
Folsom

Group
Fond Du Lac

Group
Fontana

Group
Forest Hills

Group
Fort Lauderdale

Group
Fort Washington

Group
Fort Worth

Group
Fountain Valley

Group
Frankfort

Group
Freehold

Group
Freeport

Group
Fremont

Group
Fresno

Group
Fullerton

Group
Gaithersburg

Group
Garden Grove

Group
Gardena

Group
Garland

Group
Germantown

Group
Gilroy

Group
Glen Burnie

Group
Glendale

Group
Glenview

Group
Goleta

Group
Goose Creek

Group
Granada Hills

Group
Grand Prairie

Group
Granite City

Group
Greeley

Group
Greensboro

Group
Greensburg

Group
Greenville

Group
Grove City

Group
Guayama

Group
Guaynabo

Group
Gwynn Oak

Group
Hacienda Heights

Group
Hagerstown

Group
Hamilton

Group
Hampton

Group
Hamtramck

Group
Hanford

Group
Hanover

Group
Harlingen

Group
Harvey

Group
Hawthorne

Group
Hayward

Group
Hempstead

Group
Henderson

Group
Hendersonville

Group
Henrico

Group
Hesperia

Group
Hialeah

Group
Hickory

Group
Highland

Group
Highland Park

Group
Hilliard

Group
Holland

Group
Hollister

Group
Hollywood

Group
Honolulu

Group
Houston

Group
Howell

Group
Humacao

Group
Huntington Beach

Group
Huntington Park

Group
Huntington Station

Group
Hyattsville

Group
Indianapolis

Group
Indio

Group
Irving

Group
Irvington

Group
Irwin

Group
Ithaca

Group
Jackson

Group
Jackson Heights

Group
Jacksonville

Group
Jamaica

Group
Jersey City

Group
Joliet

Group
Jonesboro

Group
Juana Diaz

Group
Kailua

Group
Kaneohe

Group
Katy

Group
Kenner

Group
Kent

Group
Knoxville

Group
La Crosse

Group
La Habra

Group
La Mesa

Group
La Mirada

Group
La Puente

Group
Laguna Hills

Group
Laguna Niguel

Group
Lake Forest

Group
Lakewood

Group
Lancaster

Group
Lansdale

Group
Laredo

Group
Las Cruces

Group
Las Vegas

Group
Lawrence

Group
Lawrenceville

Group
Lawton

Group
Lenoir

Group
Levittown

Group
Lewisville

Group
Lilburn

Group
Lindenhurst

Group
Lithonia

Group
Littleton

Group
Livermore

Group
Lockport

Group
Lodi

Group
Lombard

Group
Lompoc

Group
Long Beach

Group
Longmont

Group
Longview

Group
Los Angeles

Group
Louisville

Group
Loveland

Group
Lutz

Group
Lynn

Group
Lynnwood

Group
Lynwood

Group
Madera

Group
Madison

Group
Malden

Group
Manati

Group
Manchester

Group
Marietta

Group
Marion

Group
Marrero

Group
Martinez

Group
Martinsburg

Group
Massapequa

Group
Massillon

Group
Mayaguez

Group
Mcallen

Group
Mchenry

Group
Mechanicsburg

Group
Medford

Group
Medina

Group
Memphis

Group
Mentor

Group
Merced

Group
Meridian

Group
Mesa

Group
Mesquite

Group
Metairie

Group
Methuen

Group
Miami

Group
Michigan City

Group
Middletown

Group
Milford

Group
Mililani

Group
Milpitas

Group
Milwaukee

Group
Mission

Group
Mission Viejo

Group
Modesto

Group
Moline

Group
Montebello

Group
Moreno Valley

Group
Morganton

Group
Morristown

Group
Morrisville

Group
Mount Pleasant

Group
Mount Prospect

Group
Murfreesboro

Group
Muskegon

Group
Napa

Group
Nashville

Group
National City

Group
New Albany

Group
New Bedford

Group
New Braunfels

Group
New Brunswick

Group
New Castle

Group
New Haven

Group
New Orleans

Group
New York

Group
Newark

Group
Newburgh

Group
Norcross

Group
Norfolk

Group
Normal

Group
North Bergen

Group
North Hills

Group
North Hollywood

Group
North Las Vegas

Group
North Richland Hills

Group
North Tonawanda

Group
Norwalk

Group
O Fallon

Group
Oak Lawn

Group
Oakland

Group
Oceanside

Group
Ogden

Group
Olathe

Group
Ontario

Group
Opa Locka

Group
Opelousas

Group
Orange Park

Group
Oregon City

Group
Orlando

Group
Oviedo

Group
Oxnard

Group
Pacoima

Group
Painesville

Group
Palatine

Group
Palmdale

Group
Palo Alto

Group
Panorama City

Group
Paramount

Group
Parkville

Group
Pasadena

Group
Passaic

Group
Pawtucket

Group
Peabody

Group
Pekin

Group
Peoria

Group
Perth Amboy

Group
Pharr

Group
Philadelphia

Group
Phoenix

Group
Pico Rivera

Group
Piscataway

Group
Pittsburg

Group
Pittsfield

Group
Placentia

Group
Plainfield

Group
Plano

Group
Plymouth

Group
Pomona

Group
Pompano Beach

Group
Ponce

Group
Porterville

Group
Portland

Group
Potomac

Group
Poway

Group
Powder Springs

Group
Princeton

Group
Provo

Group
Quincy

Group
Raleigh

Group
Rancho Cordova

Group
Rancho Cucamonga

Group
Redmond

Group
Rego Park

Group
Reno

Group
Reseda

Group
Revere

Group
Reynoldsburg

Group
Rialto

Group
Richardson

Group
Richmond

Group
Ridgewood

Group
Rio Grande

Group
Rio Rancho

Group
Riverside

Group
Rochester

Group
Rock Hill

Group
Rome

Group
Roseburg

Group
Rosemead

Group
Roseville

Group
Roswell

Group
Round Rock

Group
Rowland Heights

Group
Sacramento

Group
Saginaw

Group
Saint Charles

Group
Saint Louis

Group
Saint Paul

Group
Saint Peters

Group
Salem

Group
Salina

Group
Salinas

Group
Salt Lake City

Group
San Antonio

Group
San Benito

Group
San Bernardino

Group
San Diego

Group
San Francisco

Group
San Jose

Group
San Juan

Group
San Marcos

Group
San Pablo

Group
San Pedro

Group
San Ramon

Group
San Sebastian

Group
Sandusky

Group
Sanford

Group
Santa Ana

Group
Santa Clara

Group
Santa Cruz

Group
Santa Fe

Group
Santa Maria

Group
Santee

Group
Scottsdale

Group
Seattle

Group
Sheboygan

Group
Silver Spring

Group
Simi Valley

Group
Smyrna

Group
South El Monte

Group
South Gate

Group
South Ozone Park

Group
South Richmond Hill

Group
South San Francisco

Group
Spokane

Group
Spring

Group
Spring Valley

Group
Springfield

Group
Stafford

Group
Stamford

Group
Staten Island

Group
Stockbridge

Group
Stockton

Group
Stone Mountain

Group
Strongsville

Group
Sugar Land

Group
Summerville

Group
Sumner

Group
Sun Valley

Group
Sunnyvale

Group
Sylmar

Group
Tallahassee

Group
Tampa

Group
Taunton

Group
Taylor

Group
Temecula

Group
Tempe

Group
Tinley Park

Group
Toa Alta

Group
Toa Baja

Group
Toms River

Group
Tonawanda

Group
Tracy

Group
Troy

Group
Trujillo Alto

Group
Tucson

Group
Tulare

Group
Tustin

Group
Union

Group
Union City

Group
Upland

Group
Vacaville

Group
Vallejo

Group
Valrico

Group
Van Nuys

Group
Vega Baja

Group
Ventura

Group
Victorville

Group
Virginia Beach

Group
Visalia

Group
Vista

Group
Waipahu

Group
Walnut

Group
Warren

Group
Washington

Group
Watsonville

Group
Waukegan

Group
Wayne

Group
Webster

Group
Weslaco

Group
West Chester

Group
West Covina

Group
West Haven

Group
West Jordan

Group
West Lafayette

Group
West New York

Group
West Orange

Group
Westerville

Group
Westland

Group
Westminster

Group
Wheaton

Group
Wheeling

Group
Wichita

Group
Wilkes Barre

Group
Williamsport

Group
Wilmington

Group
Winnetka

Group
Winter Park

Group
Woodbridge

Group
Woodside

Group
Woonsocket

Group
Wyandotte

Group
Wyoming

Group
Yauco

Group
Yonkers

Group
York

Group
Ypsilanti

Group
Yuma

Group
Zanesville

In [146]:
Customer_details['Customer Id'].size().nlargest(1)

Customer City
Caguas    66770
Name: Customer Id, dtype: int64

In [233]:
#10.Order date and Shipping date convert into single format
data['order date (DateOrders)']=pd.to_datetime(data['order date (DateOrders)'])
data['shipping date (DateOrders)']=pd.to_datetime(data['shipping date (DateOrders)'])

In [234]:
data['order date (DateOrders)']

0        2018-01-31 22:56:00
1        2018-01-13 12:27:00
2        2018-01-13 12:06:00
3        2018-01-13 11:45:00
4        2018-01-13 11:24:00
                 ...
180514   2016-01-16 03:40:00
180515   2016-01-16 01:34:00
180516   2016-01-15 21:00:00
180517   2016-01-15 20:18:00
180518   2016-01-15 18:54:00
Name: order date (DateOrders), Length: 180519, dtype: datetime64[ns]

In [235]:
#11.list out no. pending order from city w.r.t INDIA
data[('Order City')][(data['Order Status']=='PENDING')& (data['Order Country']=='India' )]

1             Bikaner
21           Jabalpur
45          Bangalore
46          Bangalore
382              Pune
             ...
180142    Bhubaneswar
180164           Agra
180248          Dewas
180331          Ajmer
180405          Patna
Name: Order City, Length: 537, dtype: object

In [344]:
#12.In which city highest fraud happend
data[('Order City')][(data['Order Status']=='SUSPECTED_FRAUD')].value_counts().head(50)

Managua           70
San Francisco     67
Santo Domingo     48
New York City     45
Mexico City       40
London            33
Philadelphia      32
Yakarta           32
Bangkok           30
San Salvador      26
Los Angeles       25
Zapopan           24
Chicago           24
Berl�n            24
Seattle           24
Barcelona         23
Wollongong        23
Cairo             23
Toulouse          22
Sydney            22
Villa Nueva       22
Houston           22
Viena             21
Tegucigalpa       21
Melbourne         21
Manila            21
San Pedro Sula    20
Brisbane          19
Lagos             18
Dubl�n            18
Ju�rez            17
M�rida            17
S�o Paulo         17
Bogot�            17
Milan             17
Rome              17
Tijuana           16
Valencia          16
Canberra          16
Panama City       15
Birmingham        15
Camag�ey          14
Izmir             14
Guadalajara       13
C�rdoba           13
Paris             13
Fort-de-France    12
Shangh�i          12
Mixco             12
Springfield       12
Name: Order City, dtype: int64

In [236]:
#13.Which product has maximum discount
data['Product Name'][data['Order Item Discount']==data['Order Item Discount'].max()]

12606    SOLE E35 Elliptical
Name: Product Name, dtype: object

In [340]:
#14.Which year had the minimum sales for nike product
data[(data['Product Name'].str.contains('Nike'))]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,Customer name,Customer Street Code,Customer Street Name
order date (DateOrders),,,,,,,,,,,,,,,,,,,,,
2016-03-30 04:37:00,PAYMENT,6,2,33.599998,96.000000,Late delivery,1,24,Women's Apparel,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,2016-04-05 04:37:00,Second Class,Elizabeth Pittman,7573,Golden Treasure Centre
2016-11-28 01:18:00,PAYMENT,3,2,9.100000,91.000000,Late delivery,1,24,Women's Apparel,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,2016-12-01 01:18:00,Second Class,Mary Smith,1425,Fallen Fox Arbor
2016-12-31 15:47:00,PAYMENT,5,2,-21.750000,87.000000,Late delivery,1,24,Women's Apparel,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,2017-01-05 15:47:00,Second Class,Dennis Smith,2290,Crystal Pathway
2015-10-25 06:24:00,PAYMENT,6,2,6.150000,82.000000,Late delivery,1,24,Women's Apparel,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,2015-10-31 06:24:00,Second Class,Mary Hill,6179,Noble Panda Moor
2016-10-04 22:55:00,PAYMENT,2,2,-184.779999,263.970001,Shipping on time,0,9,Cardio Equipment,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,2016-10-06 22:55:00,Second Class,Brenda Jordan,4692,Jagged Thicket
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-03-31 01:39:00,TRANSFER,5,4,-33.750000,449.959992,Late delivery,1,9,Cardio Equipment,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,2017-04-05 01:39:00,Standard Class,Eric Jensen,9660,Dewy Leaf Freeway
2017-02-10 06:27:00,TRANSFER,2,4,141.360001,434.959992,Advance shipping,0,9,Cardio Equipment,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,2017-02-12 06:27:00,Standard Class,Benjamin Smith,1800,Quiet Creek Stead
2017-06-13 02:57:00,TRANSFER,3,4,188.979996,419.959992,Advance shipping,0,9,Cardio Equipment,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,2017-06-16 02:57:00,Standard Class,Mary Rios,4167,Stony Extension
2015-04-14 05:59:00,TRANSFER,5,4,111.989998,399.959992,Late delivery,1,9,Cardio Equipment,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,2015-04-19 05:59:00,Standard Class,Richard Dickson,9383,Dewy Hollow
2015-01-18 11:21:00,TRANSFER,4,4,167.979996,399.959992,Shipping on time,0,9,Cardio Equipment,Caguas,...,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,2015-01-22 11:21:00,Standard Class,James Ortiz,7446,Rocky Inlet

In [338]:
data[(data['Product Name'].str.contains('Nike'))].valcounts()

Type                                                                          CASH
Days for shipping (real)                                                         0
Days for shipment (scheduled)                                                    0
Benefit per order                                                     -1374.859985
Sales per customer                                                            16.5
Delivery Status                                                   Advance shipping
Late_delivery_risk                                                               0
Category Id                                                                      2
Category Name                                                      As Seen on  TV!
Customer City                                                            Aguadilla
Customer Country                                                           EE. UU.
Customer Email                                                           XXXXXXXXX
Customer Id                                                                      1
Customer Password                                                        XXXXXXXXX
Customer Segment                                                          Consumer
Customer State                                                                  AL
Customer Zipcode                                                             603.0
Department Id                                                                    2
Department Name                                                            Apparel
Latitude                                                                -33.937553
Longitude                                                              -158.025986
Market                                                                      Africa
Order City                                                                  Aachen
Order Country                                                           Afganist�n
Order Customer Id                                                                1
Order Id                                                                         2
Order Item Cardprod Id                                                          19
Order Item Discount                                                            0.0
Order Item Discount Rate                                                       0.0
Order Item Id                                                                    3
Order Item Product Price                                                      22.0
Order Item Profit Ratio                                                      -2.75
Order Item Quantity                                                              1
Sales                                                                         22.0
Order Item Total                                                              16.5
Order Profit Per Order                                                -1374.859985
Order Region                                                                Canada
Order State                                                                   Abia
Order Status                                                              CANCELED
Order Zipcode                                                               1040.0
Product Card Id                                                                 19
Product Category Id                                                              2
Product Description                                                            NaN
Product Image                    http://images.acmesports.sports/Nike+Dri-FIT+C...
Product Name                                         Nike Dri-FIT Crew Sock 6 Pack
Product Price                                                                 22.0
Product Status                                                                   0
shipping date (DateOrders)                                     2015-01-03 03:30:00
Shipping Mode                                                          First Class
Customer name                                                         Aaron Berger
Customer Street Code                                                             1
Customer Street Name                                                   Amber Abbey
dtype: object

In [325]:
data

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,Customer name,Customer Street Code,Customer Street Name
order date (DateOrders),,,,,,,,,,,,,,,,,,,,,
2018-01-31 22:56:00,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2018-02-03 22:56:00,Standard Class,Cally Holloway,5365,Noble Nectar Island
2018-01-13 12:27:00,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2018-01-18 12:27:00,Standard Class,Irene Luna,2679,Rustic Loop
2018-01-13 12:06:00,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2018-01-17 12:06:00,Standard Class,Gillian Maldonado,8510,Round Bear Gate
2018-01-13 11:45:00,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2018-01-16 11:45:00,Standard Class,Tana Tate,3200,Amber Bend
2018-01-13 11:24:00,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2018-01-15 11:24:00,Standard Class,Orli Hendricks,8671,Iron Anchor Corners
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-16 03:40:00,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-01-20 03:40:00,Standard Class,Maria Peterson,1322,Broad Glade
2016-01-16 01:34:00,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-01-19 01:34:00,Second Class,Ronald Clark,7330,Broad Apple Moor
2016-01-15 21:00:00,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-01-20 21:00:00,Standard Class,John Smith,97,Burning Landing
2016-01-15 20:18:00,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-01-18 20:18:00,Standard Class,Mary Smith,2585,Silent Autumn Landing
2016-01-15 18:54:00,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2016-01-19 18:54:00,Standard Class,Andrea Ortega,697,Little Meadow

In [309]:
for date,nike in y:
    print('\nGroup')
    print(date)
    print(nike)

Group
2015
            Type  Days for shipping (real)  Days for shipment (scheduled)  \
54       PAYMENT                         6                              2
63       PAYMENT                         3                              2
66       PAYMENT                         4                              2
68       PAYMENT                         3                              2
73       PAYMENT                         6                              2
...          ...                       ...                            ...
179617  TRANSFER                         5                              4
179618  TRANSFER                         6                              4
179619  TRANSFER                         2                              4
179620  TRANSFER                         5                              4
179630  TRANSFER                         2                              4

        Benefit per order  Sales per customer   Delivery Status  \
54               6.150000           82.000000     Late delivery
63             129.350006          293.970001     Late delivery
66              81.129997          176.369995     Late delivery
68              68.779999          163.770004     Late delivery
73               7.760000           55.410000     Late delivery
...                   ...                 ...               ...
179617         131.020004          272.950012     Late delivery
179618         133.750000          272.950012     Late delivery
179619          72.889999          269.959992  Advance shipping
179620         -53.990002          269.959992     Late delivery
179630          99.470001          343.000000  Advance shipping

        Late_delivery_risk  Category Id     Category Name Customer City  ...  \
54                       1           24   Women's Apparel        Caguas  ...
63                       1            9  Cardio Equipment        Caguas  ...
66                       1           17            Cleats        Caguas  ...
68                       1           17            Cleats        Caguas  ...
73                       1           41          Trade-In        Caguas  ...
...                    ...          ...               ...           ...  ...
179617                   1           17            Cleats        Caguas  ...
179618                   1           17            Cleats        Caguas  ...
179619                   0           17            Cleats        Caguas  ...
179620                   1           17            Cleats        Caguas  ...
179630                   0           26    Girls' Apparel        Caguas  ...

       Product Description                                      Product Image  \
54                     NaN  http://images.acmesports.sports/Nike+Men%27s+D...
63                     NaN  http://images.acmesports.sports/Nike+Men%27s+F...
66                     NaN  http://images.acmesports.sports/Perfect+Fitnes...
68                     NaN  http://images.acmesports.sports/Perfect+Fitnes...
73                     NaN  http://images.acmesports.sports/Glove+It+Women...
...                    ...                                                ...
179617                 NaN  http://images.acmesports.sports/Perfect+Fitnes...
179618                 NaN  http://images.acmesports.sports/Perfect+Fitnes...
179619                 NaN  http://images.acmesports.sports/Perfect+Fitnes...
179620                 NaN  http://images.acmesports.sports/Perfect+Fitnes...
179630                 NaN  http://images.acmesports.sports/adidas+Youth+G...

                                         Product Name Product Price  \
54               Nike Men's Dri-FIT Victory Golf Polo     50.000000
63                  Nike Men's Free 5.0+ Running Shoe     99.989998
66                   Perfect Fitness Perfect Rip Deck     59.990002
68                   Perfect Fitness Perfect Rip Deck     59.990002
73      Glove It Women's Mod Oval 3-Zip Carry All Gol     21.990000
...                                               ...           ...
179617               Perfect Fitness Perfect Rip Deck     59.990002
179618               Perfect Fitness Perfect Rip Deck     59.990002
179619               Perfect Fitness Perfect Rip Deck     59.990002
179620               Perfect Fitness Perfect Rip Deck     59.990002
179630  adidas Youth Germany Black/Red Away Match Soc     70.000000

       Product Status shipping date (DateOrders)   Shipping Mode  \
54                  0        2015-10-31 06:24:00    Second Class
63                  0        2015-07-10 05:31:00    Second Class
66                  0        2015-09-26 07:41:00    Second Class
68                  0        2015-09-11 12:15:00    Second Class
73                  0        2015-07-08 19:42:00    Second Class
...               ...                        ...             ...
179617              0        2015-05-14 05:04:00  Standard Class
179618              0        2015-04-24 13:41:00  Standard Class
179619              0        2015-04-28 21:44:00  Standard Class
179620              0        2015-03-12 08:50:00  Standard Class
179630              0        2015-05-14 09:06:00  Standard Class

          Customer name Customer Street Code  Customer Street Name
54            Mary Hill                 6179      Noble Panda Moor
63           Mary Smith                 2991   Silent Deer Landing
66        Austin Sexton                 4691          Cinder Crest
68           Mary Olson                 7333            Cinder Way
73           Kyle Smith                 8344   Noble Mountain Gate
...                 ...                  ...                   ...
179617   Michael Keller                 2111       Colonial Parade
179618     Brenda Wells                 3762         Amber Estates
179619  Steven Gonzalez                 8824          Dusty Island
179620     Mary Proctor                 9483              Old Bank
179630      Mary Dunlap                 1439        Silent Pathway

[62650 rows x 53 columns]

Group
2016
            Type  Days for shipping (real)  Days for shipment (scheduled)  \
48       PAYMENT                         5                              2
49       PAYMENT                         2                              2
50       PAYMENT                         6                              2
51       PAYMENT                         2                              2
52       PAYMENT                         3                              2
...          ...                       ...                            ...
180514      CASH                         4                              4
180515     DEBIT                         3                              2
180516  TRANSFER                         5                              4
180517   PAYMENT                         3                              4
180518   PAYMENT                         4                              4

        Benefit per order  Sales per customer   Delivery Status  \
48             -30.750000          115.180000     Late delivery
49            -122.730003           79.180000  Shipping on time
50              33.599998           96.000000     Late delivery
51              24.690001           75.980003  Shipping on time
52               9.100000           91.000000     Late delivery
...                   ...                 ...               ...
180514          40.000000          399.980011  Shipping on time
180515        -613.770019          395.980011     Late delivery
180516         141.110001          391.980011     Late delivery
180517         186.229996          387.980011  Advance shipping
180518         168.949997          383.980011  Shipping on time

        Late_delivery_risk  Category Id    Category Name Customer City  ...  \
48                       1           17           Cleats       Bayamon  ...
49                       0           29    Shop By Sport        Caguas  ...
50                       1           24  Women's Apparel        Caguas  ...
51                       0           29    Shop By Sport        Caguas  ...
52                       1           24  Women's Apparel        Caguas  ...
...                    ...          ...              ...           ...  ...
180514                   0           45          Fishing      Brooklyn  ...
180515                   1           45          Fishing   Bakersfield  ...
180516                   1           45          Fishing       Bristol  ...
180517                   0           45          Fishing        Caguas  ...
180518                   0           45          Fishing        Caguas  ...

       Product Description                                      Product Image  \
48                     NaN  http://images.acmesports.sports/Perfect+Fitnes...
49                     NaN  http://images.acmesports.sports/Under+Armour+G...
50                     NaN  http://images.acmesports.sports/Nike+Men%27s+D...
51                     NaN  http://images.acmesports.sports/Under+Armour+G...
52                     NaN  http://images.acmesports.sports/Nike+Men%27s+D...
...                    ...                                                ...
180514                 NaN  http://images.acmesports.sports/Field+%26+Stre...
180515                 NaN  http://images.acmesports.sports/Field+%26+Stre...
180516                 NaN  http://images.acmesports.sports/Field+%26+Stre...
180517                 NaN  http://images.acmesports.sports/Field+%26+Stre...
180518                 NaN  http://images.acmesports.sports/Field+%26+Stre...

                                         Product Name Product Price  \
48                   Perfect Fitness Perfect Rip Deck     59.990002
49      Under Armour Girls' Toddler Spine Surge Runni     39.990002
50               Nike Men's Dri-FIT Victory Golf Polo     50.000000
51      Under Armour Girls' Toddler Spine Surge Runni     39.990002
52               Nike Men's Dri-FIT Victory Golf Polo     50.000000
...                                               ...           ...
180514      Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180515      Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180516      Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180517      Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180518      Field & Stream Sportsman 16 Gun Fire Safe    399.980011

       Product Status shipping date (DateOrders)   Shipping Mode  \
48                  0        2016-02-29 13:57:00    Second Class
49                  0        2016-10-27 14:39:00    Second Class
50                  0        2016-04-05 04:37:00    Second Class
51                  0        2016-11-01 01:31:00    Second Class
52                  0        2016-12-01 01:18:00    Second Class
...               ...                        ...             ...
180514              0        2016-01-20 03:40:00  Standard Class
180515              0        2016-01-19 01:34:00    Second Class
180516              0        2016-01-20 21:00:00  Standard Class
180517              0        2016-01-18 20:18:00  Standard Class
180518              0        2016-01-19 18:54:00  Standard Class

            Customer name Customer Street Code    Customer Street Name
48             Mary Frank                   75           Sunny Grounds
49             Mary Smith                 9731        Honey Fox Towers
50      Elizabeth Pittman                 7573  Golden Treasure Centre
51        Katherine Tyler                 8369          Sunny Crossing
52             Mary Smith                 1425        Fallen Fox Arbor
...                   ...                  ...                     ...
180514     Maria Peterson                 1322             Broad Glade
180515       Ronald Clark                 7330        Broad Apple Moor
180516         John Smith                   97         Burning Landing
180517         Mary Smith                 2585   Silent Autumn Landing
180518      Andrea Ortega                  697           Little Meadow

[62550 rows x 53 columns]

Group
2017
            Type  Days for shipping (real)  Days for shipment (scheduled)  \
64       PAYMENT                         2                              2
65       PAYMENT                         6                              2
67       PAYMENT                         2                              2
69       PAYMENT                         3                              2
70       PAYMENT                         2                              2
...          ...                       ...                            ...
179625  TRANSFER                         6                              4
179626  TRANSFER                         3                              4
179627  TRANSFER                         4                              4
179628  TRANSFER                         3                              4
179629  TRANSFER                         4                              4

        Benefit per order  Sales per customer   Delivery Status  \
64             132.289993          269.970001  Shipping on time
65              76.040001          224.979996     Late delivery
67              43.520000          167.369995  Shipping on time
69              40.490002          161.970001     Late delivery
70              20.930000          139.500000  Shipping on time
...                   ...                 ...               ...
179625          41.070000          251.960007     Late delivery
179626          92.110001          248.960007  Advance shipping
179627          76.989998          245.960007  Shipping on time
179628          67.489998          224.960007  Advance shipping
179629          37.590000          199.949997  Shipping on time

        Late_delivery_risk  Category Id     Category Name Customer City  ...  \
64                       0            9  Cardio Equipment        Caguas  ...
65                       1            9  Cardio Equipment        Caguas  ...
67                       0           17            Cleats        Caguas  ...
69                       1           17            Cleats        Caguas  ...
70                       0           24   Women's Apparel        Caguas  ...
...                    ...          ...               ...           ...  ...
179625                   1           17            Cleats        Caguas  ...
179626                   0           17            Cleats        Caguas  ...
179627                   0           17            Cleats        Caguas  ...
179628                   0           17            Cleats        Caguas  ...
179629                   0           29     Shop By Sport        Caguas  ...

       Product Description                                      Product Image  \
64                     NaN  http://images.acmesports.sports/Nike+Men%27s+F...
65                     NaN  http://images.acmesports.sports/Nike+Men%27s+F...
67                     NaN  http://images.acmesports.sports/Perfect+Fitnes...
69                     NaN  http://images.acmesports.sports/Perfect+Fitnes...
70                     NaN  http://images.acmesports.sports/Nike+Men%27s+D...
...                    ...                                                ...
179625                 NaN  http://images.acmesports.sports/Perfect+Fitnes...
179626                 NaN  http://images.acmesports.sports/Perfect+Fitnes...
179627                 NaN  http://images.acmesports.sports/Perfect+Fitnes...
179628                 NaN  http://images.acmesports.sports/Perfect+Fitnes...
179629                 NaN  http://images.acmesports.sports/Under+Armour+G...

                                         Product Name Product Price  \
64                  Nike Men's Free 5.0+ Running Shoe     99.989998
65                  Nike Men's Free 5.0+ Running Shoe     99.989998
67                   Perfect Fitness Perfect Rip Deck     59.990002
69                   Perfect Fitness Perfect Rip Deck     59.990002
70               Nike Men's Dri-FIT Victory Golf Polo     50.000000
...                                               ...           ...
179625               Perfect Fitness Perfect Rip Deck     59.990002
179626               Perfect Fitness Perfect Rip Deck     59.990002
179627               Perfect Fitness Perfect Rip Deck     59.990002
179628               Perfect Fitness Perfect Rip Deck     59.990002
179629  Under Armour Girls' Toddler Spine Surge Runni     39.990002

       Product Status shipping date (DateOrders)   Shipping Mode  \
64                  0        2017-07-24 07:16:00    Second Class
65                  0        2017-08-13 06:33:00    Second Class
67                  0        2017-07-04 09:03:00    Second Class
69                  0        2017-08-23 07:03:00    Second Class
70                  0        2017-07-24 07:16:00    Second Class
...               ...                        ...             ...
179625              0        2017-01-28 08:24:00  Standard Class
179626              0        2017-05-09 14:34:00  Standard Class
179627              0        2017-04-04 01:18:00  Standard Class
179628              0        2017-05-22 03:51:00  Standard Class
179629              0        2017-04-08 05:09:00  Standard Class

          Customer name Customer Street Code   Customer Street Name
64         Hannah Smith                 5086      Emerald Fox Farms
65          Mary Nelson                 3909  Hidden Treasure Beach
67        Michael Scott                 5703   Tawny Creek Townline
69      Vincent Krueger                 9404     Heather Bluff Dale
70         Hannah Smith                 5086      Emerald Fox Farms
...                 ...                  ...                    ...
179625    Mary Mckinney                 7168          Emerald Field
179626       Mary Pitts                 5953             Lost Plaza
179627        Ann Smith                 3422      Blue Pioneer Bend
179628      Jerry Smith                 5149        Rocky Pine Moor
179629     Megan Moreno                 1591           Foggy Meadow

[53196 rows x 53 columns]

Group
2018
            Type  Days for shipping (real)  Days for shipment (scheduled)  \
0          DEBIT                         3                              4
1       TRANSFER                         5                              4
2           CASH                         4                              4
3          DEBIT                         3                              4
4        PAYMENT                         2                              4
...          ...                       ...                            ...
176826     DEBIT                         1                              0
176827     DEBIT                         0                              0
176828     DEBIT                         0                              0
176837     DEBIT                         0                              0
179218   PAYMENT                         4                              2

        Benefit per order  Sales per customer   Delivery Status  \
0               91.250000          314.640015  Advance shipping
1             -249.089996          311.359985     Late delivery
2             -247.779999          309.720001  Shipping on time
3               22.860001          304.809998  Advance shipping
4              134.210007          298.250000  Advance shipping
...                   ...                 ...               ...
176826           0.380000           37.560001     Late delivery
176827         -62.840000           36.970001  Shipping on time
176828          15.560000           34.580002  Shipping on time
176837          12.990000           39.349998  Shipping on time
179218          26.530001           78.489998     Late delivery

        Late_delivery_risk  Category Id   Category Name Customer City  ...  \
0                        0           73  Sporting Goods        Caguas  ...
1                        1           73  Sporting Goods        Caguas  ...
2                        0           73  Sporting Goods      San Jose  ...

In [313]:

y['order date (DateOrders)'].nlargest()

order date (DateOrders)
2015                     14194    2015-12-31 23:39:00
                         14252    2015-12-31 23:39:00
                         14807    2015-12-31 23:39:00
                         51548    2015-12-31 23:39:00
                         14835    2015-12-31 22:57:00
2016                     171256   2016-12-31 23:51:00
                         171522   2016-12-31 23:51:00
                         171813   2016-12-31 23:51:00
                         172115   2016-12-31 23:51:00
                         93987    2016-12-31 23:30:00
2017                     110367   2017-12-31 23:52:00
                         42481    2017-12-31 23:31:00
                         29048    2017-12-31 23:10:00
                         124219   2017-12-31 22:49:00
                         94361    2017-12-31 22:28:00
2018                     17863    2018-01-31 23:38:00
                         52147    2018-01-31 23:17:00
                         0        2018-01-31 22:56:00
                         93905    2018-01-31 22:35:00
                         160537   2018-01-31 22:14:00
Name: order date (DateOrders), dtype: datetime64[ns]